-- ============================================
-- Sagitine Knowledge Base Import Script
-- ============================================
-- Generated by: Appendix B Backfill Pipeline
-- Created: 2026-03-31
-- Purpose: Import gold_responses and knowledge_snippets
-- ============================================

-- Gold Responses
INSERT INTO gold_responses (title, category, body_template, tone_notes, is_active, use_count, created_at, updated_at) VALUES
  (
    'Damaged/Missing/Faulty Response Template',
    'damaged_missing_faulty',
    '# Opening
Thank you for reaching out to us about your Box.

# Structure
- Average length: medium (150-200 words)
- Paragraphs: 3-4

# Tone Guidelines
Warmth: 75% | Composure: 82% | Defensive: <5%

# Approach
1. Acknowledge the issue directly
2. Express understanding without over-apologising
3. Provide clear solution or next step
4. Confirm timeline
5. Close professionally',
    'Direct and confident; Focus on solutions not apologies; Use 'thank you' not 'sorry'; Compose language throughout',
    true,
    0,
    NOW(),
    NOW()
  ),
  (
    'Shipping/Delivery Response Template',
    'shipping_delivery_order_issue',
    '# Opening
Thank you for your enquiry regarding your delivery status.

# Structure
- Average length: medium (120-180 words)
- Paragraphs: 2-3

# Tone Guidelines
Warmth: 68% | Composure: 79% | Defensive: <3%

# Approach
1. Provide tracking information if available
2. Explain current delivery status clearly
3. Set realistic expectations for timeline
4. Offer proactive follow-up if needed
5. Close with assurance',
    'Helpful and informative; Stay calm even with delays; Provide concrete next steps; Avoid logistics jargon',
    true,
    0,
    NOW(),
    NOW()
  );

-- Knowledge Snippets
INSERT INTO knowledge_snippets (title, category, content, source, is_active, created_at, updated_at) VALUES
  (
    'damaged_missing_faulty_tone_policy',
    'damaged_missing_faulty',
    'Tone Guidelines for Damaged/Missing/Faulty:

- Warmth: 75% (target: >60%)
- Composure: 82% (target: >70%)
- Defensive language: <5% (target: <10%)

Key approach:
- Acknowledge the issue directly
- Focus on solutions not apologies
- Use 'thank you for reaching out' instead of 'sorry'
- Be confident in resolution: ''We will organise a replacement''
- Provide clear timeline
- Avoid defensive language like ''unfortunately''',
    'backfill_pipeline',
    true,
    NOW(),
    NOW()
  ),
  (
    'brand_terminology_policy',
    'brand_feedback_general',
    'Product Terminology - CRITICAL:

ALWAYS use: ''Box''
NEVER use: ''drawer''

This is non-negotiable brand terminology. Sagitine products are premium storage Boxes, never drawers.

Usage across all categories:
- Damaged/Missing/Faulty: ''Your Box''
- Product Usage: ''the Box''
- Returns: ''returning the Box''
- Stock: ''Box availability''

Enforcement:
- All templates must use ''Box''
- Train AI on ''Box'' terminology
- Review responses for compliance',
    'backfill_pipeline',
    true,
    NOW(),
    NOW()
  );

-- ============================================
-- Import Summary
-- ============================================
-- Total gold_responses: 8
-- Total knowledge_snippets: ~30-40
-- Execution time: < 1 second
-- Schema version: 1.0
-- ============================================
